# Generated by Django 4.0.3 on 2023-09-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_appointment_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
